fancybox: true ## If you want to use fancybox please set the value to true.
duoshuo: ## Your duoshuo_shortname, e.g. username
disqus: ## Your disqus_shortname, e.g. username
google_search: true ## Use Google search, true/false.
baidu_search: ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: ## Use a jQuery-based local search engine, true/false.
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
shareto: true ## If you want to use the share button please set the value to true.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.

menu:
  - page: 原理
    directory: overview/overview.html
    icon: fa-home
  - page: 特性
    directory: feature/feature.html
    icon: fa-magic
  - page: 组件
    directory: component/component.html
    icon: fa-cogs
  - page: 基本应用
    directory: app/app.html
    icon: fa-cube
  - page: 测试
    directory: test/test.html
    icon: fa-blind

 

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - links

links:
  - title: 
    url: http://www.example1.com/
  - title: Card Design
    url: http://www.example2.com/
  - title: WikiStory
    url: http://www.example3.com/


# Static files
js: js
css: css

# Theme version
version: 0.0.0
